version: "1"
services:
  auth-server:
    environment:
      TAG: AUTH
    build: .
    container_name: auth-server
    network_mode: "host"
    restart: on-failure
    ports:
      - "9000:9000"
    env_file:
      - .env